FROM alpine:latest

# Install python/pip and other requirements
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install openai requests flask 

# Copy the script file into the container
COPY chatgpt.py .

# Make the script executable
RUN chmod +x ./chatgpt.py

CMD ["python3","./chatgpt.py"]
